"""16x16 Game Boy pixel icons (replace emojis). Writes preview/icons.html and
preview/icons.js (the JS block that gets pasted into game.html).
Grid chars: K darkest, D dark, M mid, L light, '.' transparent."""
import io, os

I = {}

def medal(digit):
    d = {
        '1': [".K.", "KK.", ".K.", ".K.", "KKK"],
        '2': ["KK.", "..K", ".K.", "K..", "KKK"],
        '3': ["KK.", "..K", ".K.", "..K", "KK."],
    }[digit]
    rows = [
        "...KK......KK...",
        "..KDDK....KDDK..",
        "...KDDK..KDDK...",
        "....KDDKKDDK....",
        ".....KDDDDK.....",
        ".....KKKKKK.....",
        "....KLLLLLLK....",
        "...KLMMMMMMLK...",
    ]
    for r in d:
        rows.append("...KLM" + r.replace('.', 'M') + "MMLK...")
    rows += ["...KLMMMMMMLK...", "....KLLLLLLK....", ".....KKKKKK....."]
    return "\n".join(rows)

I['medal1'] = medal('1')
I['medal2'] = medal('2')
I['medal3'] = medal('3')

I['trophy'] = """
................
..KKKKKKKKKKKK..
.KLKLLLLLLLLKLK.
K.KLLLLLLLLLLK.K
K.KLMLLLLLLMLK.K
.KKLMLLLLLLMLKK.
...KLMLLLLMLK...
....KLMMMMLK....
.....KLLLLK.....
......KLLK......
......KMMK......
.....KMMMMK.....
....KKKKKKKK....
....KMMMMMMK....
....KKKKKKKK....
"""

I['fire'] = """
.......K........
......KDK.......
......KDDK......
.....KDDDK..K...
....KDDDDDK.KK..
...KDDDLDDDKDK..
...KDDLLDDDDDK..
..KDDLLLLDDDDK..
..KDDLLLLLDDDK..
..KDLLLMLLLDDK..
..KDLLMMMLLDDK..
...KDLMMMLLDK...
....KDLLLLDK....
.....KKKKKK.....
"""

I['bolt'] = """
........KKKK....
.......KLLK.....
......KLLK......
.....KLLK.......
....KLLKKKKK....
...KLLLLLLLK....
...KKKKKLLK.....
.......KLLK.....
......KLLK......
.....KLLK.......
....KLLK........
....KLK.........
....KK..........
"""

I['star'] = """
.......KK.......
......KLLK......
......KLLK......
.KKKKKKLLKKKKKK.
.KLLLLLLLLLLLLK.
..KLLLLLLLLLLK..
...KLLLLLLLLK...
....KLLLLLLK....
....KLLLLLLK....
...KLLLKKLLLK...
...KLLK..KLLK...
..KLLK....KLLK..
..KKK......KKK..
"""

I['crown'] = """
..K....KK....K..
.KLK..KLLK..KLK.
..KK..KLLK..KK..
..KLK.KLLK.KLK..
..KLLKKLLKKLLK..
..KLLLLLLLLLLK..
..KLLMLLLLMLLK..
..KLLLLLLLLLLK..
..KKKKKKKKKKKK..
..KMMMMMMMMMMK..
..KKKKKKKKKKKK..
"""

I['gem'] = """
....KKKKKKKK....
...KLLKLLKMMK...
..KLLKLLLLKMMK..
.KKKKKKKKKKKKKK.
.KLLLKLLLLKMMMK.
..KLLKLLLLKMMK..
...KLLKLLKMMK...
....KLKLLKMK....
.....KLLLMMK....
......KLMK......
.......KK.......
"""

I['skull'] = """
....KKKKKKKK....
...KLLLLLLLLK...
..KLLLLLLLLLLK..
..KLLLLLLLLLLK..
..KLKKKLLKKKLK..
..KLKKKLLKKKLK..
..KLLKLLLLKLLK..
..KLLLLKKLLLLK..
...KLLLKKLLLK...
....KLLLLLLK....
....KLKLKLKK....
....KKLKLKLK....
.....KKKKKK.....
"""

I['beast'] = """
.KK..........KK.
.KLK........KLK.
..KLKKKKKKKKLK..
...KDDDDDDDDK...
..KDDDDDDDDDDK..
..KDLLKDDKLLDK..
..KDLKKDDKKLDK..
..KDDDDDDDDDDK..
..KDDDKKKKDDDK..
..KDDKLKKLKDDK..
..KDDKKKKKKDDK..
...KDDDDDDDDK...
....KKKKKKKK....
"""

I['muscle'] = """
..........KKKK..
.........KLLLLK.
.........KLLLLK.
..........KLLK..
..........KLLK..
....KKKK..KLLK..
...KLLLLKKLLLK..
..KLLLLLLLLLLK..
KKLLLLLLLLLLLK..
KLLLLLLLMMMLK...
KLLLLLLLLLLK....
KKKKKKKKKKK.....
"""

I['leg'] = """
......KKKKK.....
......KLLLK.....
......KLLLK.....
......KLLLK.....
......KLLLLK....
.......KLLLK....
.......KLLLK....
......KLLLK.....
......KLLLK.....
......KLLLK.....
......KLLLKKKK..
......KLLLLLLLK.
......KKKKKKKKK.
"""

I['run'] = """
........KKK.....
........KLK.....
........KKK.....
.....KKKKDK.....
....KLK.KDDK....
.......KDDKLK...
......KDDK..KK..
......KDDKK.....
.....KDK.KDK....
....KDK...KDK...
...KDK.....KDKK.
..KKK.......KK..
"""

I['calendar'] = """
....K......K....
..KKKKKKKKKKKK..
..KDDDDDDDDDDK..
..KKKKKKKKKKKK..
..KLLLLLLLLLLK..
..KLKLKLKLKLLK..
..KLLLLLLLLLLK..
..KLKLKLKLKLLK..
..KLLLLLLLLLLK..
..KLKLKLKKKLLK..
..KLLLLLLKKLLK..
..KKKKKKKKKKKK..
"""

I['hundred'] = """
..K...KKK...KKK.
.KK..K...K.K...K
..K..K...K.K...K
..K..K...K.K...K
..K..K...K.K...K
.KKK..KKK...KKK.
................
KKKKKKKKKKKKKKKK
................
KKKKKKKKKKKKKKKK
"""

I['robot'] = """
.......KK.......
.......KK.......
...KKKKKKKKKK...
...KLLLLLLLLK...
..KKLKKLLKKLKK..
..KKLKKLLKKLKK..
...KLLLLLLLLK...
...KLKKKKKKLK...
...KLLLLLLLLK...
...KKKKKKKKKK...
.....KDDDDK.....
....KDDDDDDK....
....KKKKKKKK....
"""

I['orb'] = """
.....KKKKKK.....
....KLLMMMMK....
...KLLLMMMMMK...
...KLMMMMMMMK...
...KMMMMMMMMK...
...KMMMMMMMDK...
....KMMMMMDK....
.....KKKKKK.....
....KDDDDDDK....
...KKKKKKKKKK...
"""

I['rainbow'] = """
....KKKKKKKK....
...KDDDDDDDDK...
..KDKKKKKKKKDK..
.KDKMMMMMMMMKDK.
.KDKMKKKKKKMKDK.
KDKMK......KMKDK
KDKMK......KMKDK
KDKMK......KMKDK
KKKKK......KKKKK
"""

I['owl'] = """
..K..........K..
..KK........KK..
..KDKKKKKKKKDK..
..KDDDDDDDDDDK..
..KLLLKDDKLLLK..
.KLKKLLKKLLKKLK.
.KLKKLLKKLLKKLK.
..KLLLKMMKLLLK..
..KDDDDKKDDDDK..
..KDDDDDDDDDDK..
..KDDLDDDDLDDK..
...KDDDDDDDDK...
....KKKKKKKK....
....K.K..K.K....
"""

I['sun'] = """
.......K........
..K....K....K...
...K..KKK..K....
.....KLLLK......
....KLLLLLK.....
KK.KLLLLLLLK.KK.
....KLLLLLK.....
.....KLLLK......
...K..KKK..K....
..K....K....K...
.......K........
KKKKKKKKKKKKKKKK
"""

I['loop'] = """
.....KKKKKK.....
...KKDDDDDDKK.K.
..KDDKKKKKKDDKK.
..KDK......KDDK.
.KDK......KDDDK.
.KDK.......KKKK.
.KKKK.......KDK.
.KDDDK......KDK.
.KDDK......KDK..
.KKDDKKKKKKDDK..
.K.KKDDDDDDKK...
.....KKKKKK.....
"""

I['target'] = """
.....KKKKKK.....
...KKLLLLLLKK...
..KLLKKKKKKLLK..
..KLKLLLLLLKLK..
.KLKLLKKKKLLKLK.
.KLKLKLLLLKLKLK.
.KLKLKLKKLKLKLK.
.KLKLKLKKLKLKLK.
.KLKLKLLLLKLKLK.
.KLKLLKKKKLLKLK.
..KLKLLLLLLKLK..
..KLLKKKKKKLLK..
...KKLLLLLLKK...
.....KKKKKK.....
"""

I['flag'] = """
..KKKKKKKKKKKKK.
..KKKLLKKLLKKLK.
..KKKLLKKLLKKLK.
..KLLKKLLKKLLKK.
..KLLKKLLKKLLKK.
..KKKLLKKLLKKLK.
..KKKLLKKLLKKLK.
..KKKKKKKKKKKKK.
..KK............
..KK............
..KK............
..KK............
.KKKK...........
"""

I['pencil'] = """
...........KK...
..........KLLK..
.........KDKLK..
........KDDDK...
.......KDDDK....
......KDDDK.....
.....KDDDK......
....KDDDK.......
...KLDDK........
...KLLK.........
...KKK..........
"""

I['trash'] = """
......KKKK......
...KKKKKKKKKK...
...KKKKKKKKKK...
....KLLLLLLK....
....KLKLKLLK....
....KLKLKLLK....
....KLKLKLLK....
....KLKLKLLK....
....KLLLLLLK....
....KKKKKKKK....
"""

I['x'] = """
..KK......KK....
..KKK....KKK....
...KKK..KKK.....
....KKKKKK......
.....KKKK.......
....KKKKKK......
...KKK..KKK.....
..KKK....KKK....
..KK......KK....
"""

I['question'] = """
.....KKKKKK.....
....KKLLLLKK....
...KKLKKKKLKK...
...KKK....KLK...
..........KLK...
.........KLKK...
........KLKK....
.......KLKK.....
.......KLK......
.......KKK......
................
.......KKK......
.......KLK......
.......KKK......
"""

I['lock'] = """
.....KKKKKK.....
....KK....KK....
....K......K....
....K......K....
...KKKKKKKKKK...
...KLLLLLLLLK...
...KLLLKKLLLK...
...KLLLKKLLLK...
...KLLLLKLLLK...
...KLLLLLLLLK...
...KKKKKKKKKK...
"""

I['chart'] = """
.K..............
.K.........KK...
.K.........KK...
.K.....KK..KK...
.K.....KK..KK...
.K..KK.KK..KK...
.K..KK.KK..KK...
.K..KK.KK..KK...
.KKKKKKKKKKKKKK.
"""

I['up'] = """
.......KK.......
......KKKK......
.....KKKKKK.....
....KKKKKKKK....
...KKK.KK.KKK...
.......KK.......
.......KK.......
.......KK.......
.......KK.......
"""

I['down'] = """
.......KK.......
.......KK.......
.......KK.......
.......KK.......
...KKK.KK.KKK...
....KKKKKKKK....
.....KKKKKK.....
......KKKK......
.......KK.......
"""

I['right'] = """
........KK......
........KKK.....
..KKKKKKKKKK....
..KKKKKKKKKKK...
........KKK.....
........KK......
"""

I['meat'] = """
....KKKKK.......
...KDDDDDK......
..KDDLDDDDK.....
..KDLDDDDDDK....
..KDDDDDDDDK....
...KDDDDDDK.....
....KDDDDKK.....
.....KKKKLLK....
..........KLK...
.........KLLLK..
..........KLLK..
...........KK...
"""

I['bowl'] = """
....K..K..K.....
.....K..K..K....
....K..K..K.....
................
.KKKKKKKKKKKKKK.
.KLLLLLLLLLLLLK.
..KLLLLLLLLLLK..
...KLLLLLLLLK...
....KKKKKKKK....
......KKKK......
"""

I['barbell'] = """
.KK..........KK.
KMMK........KMMK
KMMK........KMMK
KMMKKKKKKKKKKMMK
KMMKKKKKKKKKKMMK
KMMK........KMMK
KMMK........KMMK
.KK..........KK.
"""

I['heart'] = """
..KKK....KKK....
.KLLLK..KLLLK...
KLLLLLKKLLLLLK..
KLLLLLLLLLLLLK..
KLLLLLLLLLLLLK..
.KLLLLLLLLLLK...
..KLLLLLLLLK....
...KLLLLLLK.....
....KLLLLK......
.....KLLK.......
......KK........
"""


I['gear'] = """
......KKKK......
......KKKK......
..KK..KKKK..KK..
..KKKKKKKKKKKK..
...KKKKKKKKKK...
...KKKK..KKKK...
KKKKKK....KKKKKK
KKKKK......KKKKK
KKKKK......KKKKK
KKKKKK....KKKKKK
...KKKK..KKKK...
...KKKKKKKKKK...
..KKKKKKKKKKKK..
..KK..KKKK..KK..
......KKKK......
......KKKK......
"""


def norm(art):
    rows = [r for r in art.strip('\n').split('\n')]
    for r in rows:
        assert len(r) <= 16, (art[:40], r, len(r))
    rows = [r.ljust(16, '.') for r in rows]
    assert len(rows) <= 16, (art[:40], len(rows))
    pad = 16 - len(rows)
    top = pad // 2
    return ['.' * 16] * top + rows + ['.' * 16] * (pad - top)


here = os.path.dirname(os.path.abspath(__file__))
js = "const PX_ICONS = {\n" + ",\n".join(
    "  %s:[%s]" % (k, ",".join('"%s"' % r for r in norm(v))) for k, v in I.items()
) + "\n};\n"
io.open(os.path.join(here, 'icons.js'), 'w', encoding='utf-8').write(js)

page = """<!DOCTYPE html><html lang="zh-TW"><head><meta charset="UTF-8"><title>像素圖示</title>
<style>body{background:#9bbc0f;color:#0f380f;font-family:sans-serif;padding:16px}
.g{display:flex;flex-wrap:wrap;gap:14px}.i{text-align:center;font-size:12px;font-weight:700}
.t{background:#9bbc0f;border:3px solid #0f380f;line-height:0;display:inline-block;padding:4px}
.dark{background:#0f380f;padding:8px;margin-top:16px;display:inline-flex;gap:8px}</style></head><body>
<div class="g" id="g"></div>
<script src="icons.js"></script><script>
const PAL={K:'#0f380f',D:'#306230',M:'#8bac0f',L:'#e0f8a0'};
function svg(g,s){let r='';g.forEach((row,y)=>{for(let x=0;x<16;x++){const f=PAL[row[x]];if(f)r+='<rect x="'+x+'" y="'+y+'" width="1" height="1" fill="'+f+'"/>';}});
return '<svg width="'+16*s+'" height="'+16*s+'" viewBox="0 0 16 16" shape-rendering="crispEdges">'+r+'</svg>';}
for(const k in PX_ICONS){document.getElementById('g').innerHTML+='<div class="i"><div class="t">'+svg(PX_ICONS[k],4)+'</div><div>'+k+'</div></div>';}
</script></body></html>"""
io.open(os.path.join(here, 'icons.html'), 'w', encoding='utf-8').write(page)
print(len(I), 'icons')
