"""Draft sprites for remaining exercises; writes them into sprites.html.
Grid chars: K darkest, D dark, M mid, L light, '.' transparent. 20x20."""
import io, re, os

S = {}

S['上斜臥推'] = """
...........KKK......
..........KMMMK.....
.........KMMDMMK....
.........KMDKDMK....
.........KMMDMMK....
...KKK....KMMMK.....
..KLLLK....KKK......
..KLLKK...KLK.......
..KLLLK..KLK........
..KKKKKKKDDK........
..KKDDDDDDDK........
...KKDDDDDDDK.......
....KKDDDDDDKKKKK...
.....KKDDDDDDDDDDK..
......KKKKKKKKKKDK..
.......KKKKKKKKKDK..
........KD....KDDK..
........KD....KKKKK.
"""

S['上斜啞鈴臥推'] = """
....................
....................
...........KKK......
..........KMMMK.....
..........KMKMK.....
...KKK....KMMMK.....
..KLLLK....KKK......
..KLLKK...KLK.......
..KLLLK..KLK........
..KKKKKKKDDK........
..KKDDDDDDDK........
...KKDDDDDDDK.......
....KKDDDDDDKKKKK...
.....KKDDDDDDDDDDK..
......KKKKKKKKKKDK..
.......KKKKKKKKKDK..
........KD....KDDK..
........KD....KKKKK.
"""

S['高位下拉'] = """
........KKKK........
.........KK.........
.KKKKKKKKKKKKKKKKKK.
.KLK...KKKKKK...KLK.
.KLK..KLLLLLLK..KLK.
..KLK.KLKLLKLK.KLK..
...KLKKLLLLLLKKLK...
....KLKKKLLKKKLK....
.....KLDDDDDDDDLK...
.....KKDDDDDDDDKK...
......KDDDDDDDDK....
......KDDDDDDDDK....
...KKKKDDDDDDDDKKKK.
.....KLLLK..KLLLK...
.....KLLK....KLLK...
.....KLLK....KLLK...
....KKKKK...KKKKK...
"""

S['坐姿划船'] = """
....................
....................
....................
....KKK.............
...KLLLK............
...KLLKK............
...KLLLK............
....KKK.............
...KDDDKKKKK.....KKK
...KDDDLLLLKDDDDDKMK
...KDDDKKKKK.....KKK
...KDDDK.........KMK
...KDDDDDDDDDDDDKKMK
...KKKKKKKKKKKKKK.KK
..KKKKKKK...........
..KD...KD...........
..KD...KD...........
"""

S['划船'] = """
....................
....................
....................
............KKK.....
....KKKKKKKKLLLK....
...KDDDDDDDKLLKK....
...KDDDDDDDKLLLK....
...KKDDDDDKKKKK.....
....KDDK..KLK.......
....KDDK..KKK.......
....KDDK.KMMMK......
.....KDDKMMDMMK.....
.....KDDKMDKDMK.....
.....KDDKMMDMMK.....
....KDDK.KMMMK......
....KLLK..KKK.......
...KKKKK............
KKKKKKKKKKKKKKKKKKKK
"""

S['肩推'] = """
....................
.KK..............KK.
KMMK............KMMK
KMMKKKKKKKKKKKKKKMMK
KMMKKLK......KLKKMMK
.KK.KLKKKKKKKKLK.KK.
....KLKLLLLLLKLK....
....KLKLKLLKLKLK....
....KLKLLLLLLKLK....
....KLKKKLLKKKLK....
....KKDDDDDDDDKK....
.....KDDDDDDDDK.....
......KDDDDDDK......
......KDDKKDDK......
......KLLKKLLK......
......KLLKKLLK......
.....KKKKKKKKKK.....
"""

S['側平舉'] = """
....................
.......KKKKKK.......
......KLLLLLLK......
......KLKLLKLK......
......KLLLLLLK......
.......KKLLKK.......
KKK...KKDDDDKK...KKK
KMKKKKDDDDDDDDKKKKMK
KMLLLLLDDDDDDLLLLLMK
KMKKKKKDDDDDDKKKKKMK
KKK...KDDDDDDK...KKK
......KDDDDDDK......
......KDDKKDDK......
......KLLKKLLK......
......KLLKKLLK......
......KLLKKLLK......
.....KKKKKKKKKK.....
"""

S['三頭下壓'] = """
....................
..............KKK.KK
......KKK.....KMK.KD
.....KLLLK....KKK.KD
.....KLLKK.....K..KD
.....KLLLK....K...KD
......KKK.....K...KD
.....KDDDK...K....KD
.....KDDLK...K....KD
.....KDDLK..K.....KD
.....KDDLLK.K.....KD
.....KDDKLLKKK....KD
.....KDDDK........KD
.....KDKDK........KD
.....KDKDK........KD
.....KLKLK........KD
....KKKKKKK.....KKKK
"""

S['硬舉'] = """
....................
....................
............KKK.....
...........KLLLK....
...........KLLKK....
........KKKKLLLK....
......KKDDDDKKK.....
....KKDDDDDDKLK.....
...KDDDDDDKKKLK.....
...KDDDDKK..KLK.....
...KDDDDK...KLK.....
....KDDK....KKK.....
....KDDK...KMMMK....
.....KDDK.KMMDMMK...
.....KDDK.KMDKDMK...
....KDDK..KMMDMMK...
....KLLK...KMMMK....
...KKKKK....KKK.....
KKKKKKKKKKKKKKKKKKKK
"""

S['羅馬尼亞硬舉'] = """
....................
............KKK.....
...........KLLLK....
...........KLLKK....
........KKKKLLLK....
......KKDDDDKKK.....
....KKDDDDDDKLK.....
...KDDDDDDKKKLK.....
...KDDDDKK..KKK.....
...KDDDDK..KMMMK....
....KDDK..KMMDMMK...
....KDDK..KMDKDMK...
....KDDK..KMMDMMK...
....KDDK...KMMMK....
....KDDK....KKK.....
....KDDK............
....KLLK............
...KKKKKK...........
KKKKKKKKKKKKKKKKKKKK
"""

S['腿推'] = """
....................
...........KK.......
...........KMK......
..........KKKMK.....
.........KDKKKMK....
........KDDK.KKMK...
.KKK...KDDK...KKMK..
KLLLK.KDDK.....KKK..
KLLKKKDDK...........
KLLLKDDDK...........
.KKKDDDDK...........
..KDDDDK............
.KKKKKKKKKK.........
.KMMMMMMMMK.........
.KKKKKKKKKK.........
..KD....KD..........
..KD....KD..........
"""

S['腿彎舉'] = """
....................
....................
....................
................KK..
...............KMMK.
...............KMMK.
...............KLK..
...............KLK..
.KKK...........KLK..
KDDDKKKKKKKKKKKKLK..
KDDDKDDDDDDDDDDDDK..
.KKKKKKKKKKKKKKKKK..
.KMMMMMMMMMMMMMMK...
.KKKKKKKKKKKKKKKK...
..KD..........KD....
..KD..........KD....
"""

S['腿伸展'] = """
....................
....................
....KKK.............
...KLLLK............
...KLLKK............
...KLLLK............
..KKKKK.............
.KKDDDK.............
.KKDDDK.............
.KKDDDK.............
.KKDDDKKKKKKKKKKKKK.
.KKDDDDDDDDDLLLLLLKK
.KKKKKKKKKKKKKKMMMKK
.KMMMMMMMMMK..KMMMK.
.KKKKKKKKKKK...KKK..
...KD....KD.........
...KD....KD.........
"""

S['小腿'] = """
....................
........KKK.........
.......KLLLK........
.......KLLKK........
.......KLLLK........
........KKK.........
.......KDDDK........
.......KDDDK........
.......KDLDK........
.......KDLDK........
.......KDDDK........
.......KDDDK...K....
........KDK...KKK...
........KLK..K.K.K..
........KLK....K....
........KLKK...K....
.........KLK........
.....KKKKKKKKK......
.....KMMMMMMMK......
.....KKKKKKKKK......
"""

S['腹部'] = """
....................
....................
....................
....................
....KKK.............
...KLLLK......KK....
...KLLKK.....KDDK...
...KLLLKK...KDDDDK..
....KKKDDK.KDDKKDDK.
......KDDDKDDK..KLK.
.......KDDDDK...KLK.
........KDDK....KLK.
........KKKK...KKKK.
KKKKKKKKKKKKKKKKKKKK
"""

S['哈克深蹲'] = """
K...................
KK..................
.KK..KKK............
..KKKLLLK...........
...KKLLKK...........
...KKLLLK...........
....KKKKDK..........
.....KKDDDK.........
......KKDDDK........
.......KKDDDKKKK....
........KKDDDDDDK...
.........KKKKKKDDK..
..........KK...KDK..
...........KK..KDK..
............KK.KDK..
.............KKKDK..
..............KKKKK.
............KKKKKKKK
"""

S['臀推'] = """
....................
....................
....................
.........KKK........
........KMMMK.......
.......KMMDMMK......
.KKK...KMDKDMK......
KLLLK..KMMDMMK......
KLLKKKKKKMMMKKKKK...
KLLLKDDDDKKKDDDDDK..
KKKKKKKDDDDDDDDDDK..
KMMMMMK.......KDK...
KKKKKKK.......KDK...
.KD.KD........KDK...
.KD.KD........KDK...
.KD.KD.......KKKK...
KKKKKKKKKKKKKKKKKKKK
"""


def norm(art):
    rows = [r for r in art.strip('\n').split('\n')]
    for r in rows:
        assert len(r) <= 20, (r, len(r))
    rows = [r.ljust(20, '.') for r in rows]
    # vertically center
    pad = 20 - len(rows)
    top = pad // 2
    return ['.' * 20] * top + rows + ['.' * 20] * (pad - top)


here = os.path.dirname(os.path.abspath(__file__))
p = os.path.join(here, 'sprites.html')
s = io.open(p, encoding='utf-8').read()
blocks = []
for name, art in S.items():
    rows = norm(art)
    blocks.append("  '%s': [\n%s\n  ]" % (name, ",\n".join('    "%s"' % r for r in rows)))
extra = ",\n".join(blocks)
# drop previously inserted extras, then append after the curl sprite
s = re.sub(r"(\n  '二頭彎舉': \[.*?\n  \]).*?(\n\};)", r"\1,\n" + extra.replace('\\', '\\\\') + r"\2", s, flags=re.S)
io.open(p, 'w', encoding='utf-8').write(s)
print(len(S), 'sprites written')
